name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backend sanity check
        env:
          OPENAI_API_KEY: dummy
          LIFI_API_KEY: dummy
        run: |
          python -c "import main; print('Imported main OK')"

      - name: Streamlit version
        run: |
          streamlit --version

